# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\DJ_programming\DJ_程序设计方法学作业\DJ_打飞机\resources\UI\game_Form_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogGame(object):
    def setupUi(self, DialogGame):
        DialogGame.setObjectName("DialogGame")
        DialogGame.resize(440, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogGame.sizePolicy().hasHeightForWidth())
        DialogGame.setSizePolicy(sizePolicy)
        DialogGame.setMinimumSize(QtCore.QSize(440, 650))
        DialogGame.setMaximumSize(QtCore.QSize(440, 650))
        self.gridLayout = QtWidgets.QGridLayout(DialogGame)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_game = QtWidgets.QGraphicsView(DialogGame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_game.sizePolicy().hasHeightForWidth())
        self.graphicsView_game.setSizePolicy(sizePolicy)
        self.graphicsView_game.setMinimumSize(QtCore.QSize(420, 630))
        self.graphicsView_game.setMaximumSize(QtCore.QSize(420, 630))
        self.graphicsView_game.setObjectName("graphicsView_game")
        self.gridLayout.addWidget(self.graphicsView_game, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(DialogGame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(DialogGame)
        QtCore.QMetaObject.connectSlotsByName(DialogGame)

    def retranslateUi(self, DialogGame):
        _translate = QtCore.QCoreApplication.translate
        DialogGame.setWindowTitle(_translate("DialogGame", "飞机大战"))
        self.pushButton.setText(_translate("DialogGame", "测试"))
